export const elements = {
    form: document.querySelector('.form__input--container'),
    formInputs: document.querySelectorAll('#formWord,#formMeaning,#formSample,#formDetails'),
    wordList: document.querySelector('.list__words--results'),
    deleteWord: document.querySelector('.delete'),
    wordContainer: document.querySelector('.list__words--results'),
    searchQuery: document.querySelector('#search'),
    searchButton: document.querySelector('.list__header--search--icon'),
    searchForm: document.querySelector('.list__header--search'),
    navHome: document.querySelector('#home'),
    navList: document.querySelector('#list'),
    navHomeButton: document.querySelector('#home_button'),
    navListButton: document.querySelector('#list_button'),
    firstTab: document.querySelector('#form'),
    secondTab: document.querySelector('#wordList'),
    saveBtn: document.querySelector('#saveBtn'),
    snackBar: document.getElementById("snackbar"),
    appSpinner: document.querySelector('#app_loader'),
    loginScreen: document.querySelector('.login'),
    dashboard: document.querySelector('.dashboard'),
    logoutBtn: document.querySelector('#logout')
};